version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: unless-stopped
