version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000 --workers 4
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    command: sh -c "npm run build && npm run start"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api
    restart: always
